language: ruby
cache: bundler

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y autoconf automake boost1.55 libffi-dev
  - gem update bundler

rvm:
  - 2.3.1

script: bundle exec rake spec
services:
  - redis-server

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

after_success:
  - bundle exec codeclimate-test-reporter
